[package]
name = "yinsh"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
enum_dispatch = "0.3.11"
itertools = "0.10.5"
macroquad = "0.3.25"
num = "0.4.0"
