name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    name: Build and test
    runs-on: ${{ matrix.config.os }}
    strategy:
      fail-fast: false
      matrix:
        config:
          - { os: ubuntu-latest, target: 'x86_64-unknown-linux-gnu' }
          - { os: ubuntu-latest, target: 'wasm32-unknown-unknown' }
        include:
          - os: ubuntu-latest
            packages: libx11-dev libxi-dev libgl1-mesa-dev libasound2-dev

    steps:
      - uses: actions/checkout@v2
      - name: Install packages (Linux)
        run: |
          sudo apt-get update
          sudo apt-get -yq --no-install-suggests --no-install-recommends install ${{ matrix.packages }}
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: ${{ matrix.config.target }}
      - uses: actions-rs/cargo@v1
        with:
          command: build
          args: --all-targets --target=${{ matrix.config.target }}
      - uses: actions-rs/cargo@v1
        with:
          command: test
          args: --all-targets --target=${{ matrix.config.target }}
